inteiro = (int(input("Digite um numero inteiro: ")))
res = inteiro * 1
print("{} x 1 = {}".format(inteiro, res))
res = inteiro * 2
print("{} x 2 = {}".format(inteiro, res))
res = inteiro * 3
print("{} x 3 = {}".format(inteiro, res))
res = inteiro * 4
print("{} x 4 = {}".format(inteiro, res))
res = inteiro * 5
print("{} x 5 = {}".format(inteiro, res))
res = inteiro * 6
print("{} x 6 = {}".format(inteiro, res))
res = inteiro * 7
print("{} x 7 = {}".format(inteiro, res))
res = inteiro * 8
print("{} x 8 = {}".format(inteiro, res))
res = inteiro * 9
print("{} x 9 = {}".format(inteiro, res))
res = inteiro * 10
print("{} x 10 = {}".format(inteiro, res))